apiVersion: batch/v1
kind: Pod
metadata:
  name: alpine
  namespace: default
spec:
  containers:
  - name: alpine
    image: alpine
    command:
      - sleep
      - "5"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
    