apiVersion: v1
kind: Pod
metadata:
  name: alpine2
  namespace: default
spec:
  containers:
  - name: alpine2
    image: alpine
    command:
      - sleep
      - "5"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
    
